FROM sitespeedio/sitespeed.io:8.0.6

LABEL "com.github.actions.name"="Run sitespeed.io"
LABEL "com.github.actions.description"="Test the performance of your web site"
LABEL "com.github.actions.icon"="monitor"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="https://github.com/sitespeedio/actions"
LABEL "homepage"="https://www.sitespeed.io/"
LABEL "maintainer"="Peter Hedenskog <peter@soulgalore.com>"

